// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  column: dynamic(() => import("./Column")),
  conductors: dynamic(() => import("./Conductors")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  intro: dynamic(() => import("./Intro")),
  singers: dynamic(() => import("./Singers")),
};
